version: '3.8'
services:
  frontend:
    build: 
      context: ./FE_premier-zone
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - football-network
    environment:
      - NODE_ENV=production
    depends_on:
      - backend  # Ensures backend starts first

  backend:
    build: 
      context: ./premier-zone
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    networks:
      - football-network
    environment:
      - SPRING_PROFILE=prod

networks:
  football-network:
    driver: bridge